### ISSUE TITLE
Exception: MailKit.Security.AuthenticationException: 'Authentication failed.'

### ISSUE THREAD

**Issue by boniu89** [BlueHippoGithub/IMAP-OAuth-2.0-Example#2]
Hello, I have the same problem like 'hm to'
Line:  await client.AuthenticateAsync(oauth2);
MailKit.Security.AuthenticationException
  HResult=0x80131500
  Message=Authentication failed.
  Source=MailKit
 This exception was originally thrown at this call stack:
    [External Code]
    OAuthApplication.MailHandler.IMAPConnectAsync(MailKit.Net.Imap.ImapClient, OAuthApplication.AccessTokenModel, MailKit.FolderAccess) in MailHandler.cs
    [External Code]
    OAuthApplication.MailHandler.GetFirstUnreadMessageAsync(OAuthApplication.AccessTokenModel) in MailHandler.cs
    [External Code]
    <Program>$.<Main>$(string[]) in Program.cs

API Permission:
Microsoft Graph: IMAP.AccessAsUser.All, offline_access, openid, SMTP.Send, User.Read
Office 365 Exchange Online: IMAP.AccessAsApp, Mail.Read, Mail.ReadWrite, Mail.Send.
All of them have Granted for.... with green sign. (My admin did it, because I am only User Role)

Admin also did operation in Powershell.

Get-MailboxPermission -Identity xxxx | Format-List
IsOwner         : False
AccessRights    : {FullAccess, ReadPermission}
Deny            : False
InheritanceType : All
User            : NT AUTHORITY\SELF
UserSid         : xxxx
Identity        : xxx
IsInherited     : False
IsValid         : True
ObjectState     : Unchanged

Can anyone help me?

**Comment by BlueHippoGithub** [comment]
Are you sure admin gave the rights as application and not delegated? And did he use the Add-MailboxPermission part and everything as well?

**Comment by boniu89** [comment]
> Are you sure admin gave the rights as application and not delegated? And did he use the Add-MailboxPermission part and everything as well?

Can You explain words "not delegated"?
Admin run Get-MailboxPermission -Identity xxxx | Format-List where xxxx is my email which I want to connect.

**Comment by boniu89** [comment]
A some screenshoots from Azure:
https://ibb.co/p0FBy63
https://ibb.co/68Ndrk2
https://ibb.co/hFkDZ4r

**Comment by BlueHippoGithub** [comment]
The graph application looks just fine. You need to use add mailbox permission, not get mailboxpermission, get doesn't change anything. Watch my video again and notice the part where I show you how to create the service principal and assign full access to it.


________________________________

**Comment by boniu89** [comment]
Hi again,
in your video/github You have:
Add-MailboxPermission -Identity "MAILTOACCESS" -User $app.ObjectId -AccessRights FullAccess

On the page [https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#use-client-credentials-grant-flow-to-authenticate-imap-and-pop-connections](url)
I see:
New-ServicePrincipal -AppId <APPLICATION_ID> -ServiceId <OBJECT_ID> [-Organization <ORGANIZATION_ID>]
Get-ServicePrincipal | fl
Add-MailboxPermission -Identity "john.smith@contoso.com" -User 
**<SERVICE_PRINCIPAL_ID>** -AccessRights FullAccess

Value $app.ObjectId equals <SERVICE_PRINCIPAL_ID> ?
Which version is correct?

**Comment by BlueHippoGithub** [comment]
It's the object ID of the azure ad service principal. $app is defined as a variable, it's the first line on the github page.

$app = Get-AzureADServicePrincipal -SearchString "IMAP OAuth 2.0"

Hope this helps
________________________________

**Comment by boniu89** [comment]
I understand what is $app :)
But I think that $app.ObjectId it is not the same value for Service Principal_ID.
I think correct or wrong?

**Comment by boniu89** [comment]
Now works. 
Thank You :)
